const img =
  "https://img.freepik.com/free-photo/fresh-healthy-fruits-straw-basket-generative-ai_188544-11999.jpg?w=740&t=st=1705852041~exp=1705852641~hmac=c2fa6c42065d01e4bd2793e549c83d4d41964bf435c91f8f2e2357b8e644ebe7";

const blogsData = [
  {
    id: "0",
    title: "Orange",
    subtitle: "Orange",
    img: img,
    price: "$5.50",
    createdAt: "2024-01-21T12:00:00Z",
    imageUrl: img,
    about: <p>test</p>,
  },
  {
    id: "0",
    title: "Tangerine",
    subtitle: "Tangerine",
    img: img,
    price: "$3.00",
    createdAt: "",
    imageUrl: img,
    about: <p>test</p>,
  },
  {
    id: "0",
    title: "Raspberry",
    subtitle: "Raspberry",
    img: img,
    price: "$10.00",
    createdAt: "",
    imageUrl: img,
    about: <p>test</p>,
  },
  {
    id: "0",
    title: "Lemon",
    subtitle: "Lemon",
    img: img,
    price: "$5.30",
    createdAt: "",
    imageUrl: img,
    about: <p>test</p>,
  },
  {
    id: "0",
    title: "Avocado",
    subtitle: "Avocado",
    img: img,
    price: "$15.70",
    createdAt: "",
    imageUrl: img,
    about: <p>test</p>,
  },
  {
    id: "0",
    title: "Lemon 2",
    subtitle: "Lemon 2",
    img: img,
    price: "$8.00",
    createdAt: "",
    imageUrl: img,
    about: <p>test</p>,
  },
  {
    id: "0",
    title: "Banana",
    subtitle: "Banana",
    img: img,
    price: "$7.50",
    createdAt: "",
    imageUrl: img,
    about: <p>test</p>,
  },
  {
    id: "0",
    title: "Watermelon",
    subtitle: "Watermelon",
    img: img,
    price: "$12.20",
    createdAt: "",
    imageUrl: img,
    about: <p>test</p>,
  },
];

export default blogsData;
